//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multipurpose_card
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersofsinglecard
    {
        public string userid { get; set; }
        public string passwords { get; set; }
        public string acc1 { get; set; }
        public string acc1pass { get; set; }
        public string acc2 { get; set; }
        public string acc2pass { get; set; }
        public string username { get; set; }
        public string acc1name { get; set; }
        public string acc2name { get; set; }
    }
}
