//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiruWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankuser
    {
        public bankuser()
        {
            this.useraccounts = new HashSet<useraccount>();
        }
    
        public string username { get; set; }
        public string userid { get; set; }
        public string passwords { get; set; }
    
        public virtual ICollection<useraccount> useraccounts { get; set; }
    }
}
