//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiruWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public string bankid { get; set; }
        public string bankname { get; set; }
        public string bankurl { get; set; }
    }
}
