//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiruWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public string userid { get; set; }
        public string bankid { get; set; }
        public string accountid { get; set; }
        public string accounttype { get; set; }
        public string accountpassword { get; set; }
    
        public virtual bankuser bankuser { get; set; }
    }
}
